// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYps7sfURblMVzMbcmBqNe2_ACaME0EzA',
    appId: '1:553549155360:web:5862b9ce7875ff0e04c045',
    messagingSenderId: '553549155360',
    projectId: 'cute-jumps-game',
    authDomain: 'cute-jumps-game.firebaseapp.com',
    storageBucket: 'cute-jumps-game.firebasestorage.app',
    measurementId: 'G-0SBCTLKC10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiHTtJ6EJk52m9vjF7hzxFhXUBOZaA7gg',
    appId: '1:553549155360:android:0701a62fa1c56c1304c045',
    messagingSenderId: '553549155360',
    projectId: 'cute-jumps-game',
    storageBucket: 'cute-jumps-game.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQZVJvL0FPPWqF_9ypVR7gTRZlv2Ktjnk',
    appId: '1:553549155360:ios:96cc69c08678782704c045',
    messagingSenderId: '553549155360',
    projectId: 'cute-jumps-game',
    storageBucket: 'cute-jumps-game.firebasestorage.app',
    iosBundleId: 'com.example.cuteGame',
  );
}
